// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThinkAboutApi.Models;

namespace ThinkAboutApi.Migrations.DomesticDogs
{
    [DbContext(typeof(DomesticDogsContext))]
    [Migration("20190621130844_table of domestic")]
    partial class tableofdomestic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThinkAboutApi.Models.DomesticDogsDetails", b =>
                {
                    b.Property<int>("code")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("breed")
                        .IsRequired();

                    b.Property<string>("description");

                    b.Property<bool>("gender");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)))
                        .HasColumnType("varchar(15)");

                    b.HasKey("code");

                    b.ToTable("DomesticDogs");
                });
#pragma warning restore 612, 618
        }
    }
}
